# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "feature-branch" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps: 
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - name: Checkout to another branch
        run: git checkout -b feature-branch
      - name: Commit changes
        run: git commit -m "commit message"
      - name: Push changes to branch
        run: git push origin feature-branch
      - name: Merge changes into main branch
        run: git merge feature-branch
      - name: Push changes to main branch
        run: git push origin main
